services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp
      - API_KEY=your-api-key-for-happyrobot-integration
      - FMCSA_API_KEY=your-fmcsa-api-key
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    command: >
      sh -c "
        python app/core/seed_data.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "


volumes:
  postgres_data: 